/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Funcionario;
import Model.Paciente;
import javax.swing.JOptionPane;

/**
 *
 * @author laborda
 */
public class Vw_CadastroPaciente extends javax.swing.JFrame {

    /**
     * Creates new form Vw_Principal
     */
    public Vw_CadastroPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_Nome = new javax.swing.JTextField();
        txt_Rg = new javax.swing.JTextField();
        txt_Cpf = new javax.swing.JTextField();
        txt_Fone = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        txt_Rua = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        txt_Casa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_Bairro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setTitle("Cadastro Paciente");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CADASTRO PACIENTE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 160, 30));

        jLabel2.setText("NOME:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jLabel3.setText("RG:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jLabel4.setText("CPF:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel5.setText("FONE:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        jLabel6.setText("EMAIL:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        jLabel7.setText("RUA:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        jLabel8.setText("CASA:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));
        getContentPane().add(txt_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 142, -1));
        getContentPane().add(txt_Rg, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 142, -1));
        getContentPane().add(txt_Cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 142, -1));

        txt_Fone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FoneActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Fone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 142, -1));
        getContentPane().add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 142, -1));
        getContentPane().add(txt_Rua, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 142, -1));

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 130, 70));

        jButton2.setText("  Pesquisar Nome");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 139, 30));

        jButton3.setText("Alterar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 110, 30));

        jButton4.setText("Excluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 100, 30));

        jButton5.setText("Sair");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 100, 30));

        jButton6.setText("  Pesquisar Cpf");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 139, 30));

        jButton7.setText("Limpar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 110, 30));
        getContentPane().add(txt_Casa, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 142, -1));

        jLabel10.setText("BAIRRO:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));
        getContentPane().add(txt_Bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 142, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/paper.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_FoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FoneActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Paciente pac = new Paciente();
        
        if(Backup.pac.PesquisarNome(txt_Nome.getText())!=null){
            
            pac = Backup.pac.PesquisarNome(txt_Nome.getText());
            
            txt_Nome.setText(pac.getNome());
            txt_Rg.setText(pac.getRg());
            txt_Cpf.setText(pac.getCpf());
            txt_Fone.setText(pac.getFone());
            txt_Email.setText(pac.getEmail());
            txt_Rua.setText(pac.getRua());
            txt_Casa.setText(pac.getCasa());
            txt_Bairro.setText(pac.getBairro());
            
        }
         else{
            
            JOptionPane.showMessageDialog(null, "Usuario nao Cadastrado");
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        
        Paciente pac = new Paciente();
        
        if(Backup.pac.PesquisaCpf(txt_Cpf.getText())!=null){
            
            pac = Backup.pac.PesquisaCpf(txt_Cpf.getText());
            
            txt_Nome.setText(pac.getNome());
            txt_Rg.setText(pac.getRg());
            txt_Cpf.setText(pac.getCpf());
            txt_Fone.setText(pac.getFone());
            txt_Email.setText(pac.getEmail());
            txt_Rua.setText(pac.getRua());
            txt_Casa.setText(pac.getCasa());
            txt_Bairro.setText(pac.getBairro());
        }
        
        else{
            
            JOptionPane.showMessageDialog(null, "Usuario nao Cadastrado");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Paciente paciente= new Paciente();

        paciente.setNome(txt_Nome.getText());
        paciente.setRg(txt_Rg.getText());
        paciente.setCpf(txt_Cpf.getText());
        paciente.setFone(txt_Fone.getText());
        paciente.setEmail(txt_Email.getText());
        paciente.setRua(txt_Rua.getText());
        paciente.setCasa(txt_Casa.getText());
        paciente.setBairro(txt_Bairro.getText());

        Backup.pac.Cadastro(paciente);
        JOptionPane.showMessageDialog(null,"Cadastro Realizado com Sucesso");

        txt_Nome.setText("");
        txt_Rg.setText("");
        txt_Cpf.setText("");
        txt_Fone.setText("");
        txt_Email.setText("");
        txt_Rua.setText("");
        txt_Casa.setText("");
        txt_Bairro.setText("");
        txt_Nome.requestFocus();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        txt_Nome.setText("");
        txt_Rg.setText("");
        txt_Cpf.setText("");
        txt_Fone.setText("");
        txt_Email.setText("");
        txt_Rua.setText("");
        txt_Casa.setText("");
        txt_Bairro.setText("");
        txt_Nome.requestFocus();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        Paciente paciente = new Paciente();
        
        paciente.setNome(txt_Nome.getText());
                 
        txt_Nome.setText("");
        txt_Rg.setText("");
        txt_Cpf.setText("");
        txt_Fone.setText("");
        txt_Email.setText("");
        txt_Rua.setText("");
        txt_Casa.setText("");
        txt_Bairro.setText("");
        txt_Nome.requestFocus();
        JOptionPane.showMessageDialog(null, "Cadastro Excluído com Sucesso");
        
                 
        Backup.pac.Excluir(paciente);
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        Paciente paciente = new Paciente();
        
        paciente.setNome(txt_Nome.getText());
        paciente.setRg(txt_Rg.getText());
        paciente.setCpf(txt_Cpf.getText());
        paciente.setFone(txt_Fone.getText());
        paciente.setEmail(txt_Email.getText());
        paciente.setRua(txt_Rua.getText());
        paciente.setCasa(txt_Casa.getText());
        paciente.setBairro(txt_Bairro.getText());
        
        Backup.pac.Alterar(paciente);
        
        txt_Nome.setText("");
        txt_Rg.setText("");
        txt_Cpf.setText("");
        txt_Fone.setText("");
        txt_Email.setText("");
        txt_Rua.setText("");
        txt_Casa.setText("");
        txt_Bairro.setText("");
        txt_Nome.requestFocus();       
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
         Vw_FuncGerente tela= new Vw_FuncGerente();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vw_CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vw_CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vw_CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vw_CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vw_CadastroPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_Bairro;
    private javax.swing.JTextField txt_Casa;
    private javax.swing.JTextField txt_Cpf;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_Fone;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_Rg;
    private javax.swing.JTextField txt_Rua;
    // End of variables declaration//GEN-END:variables
}
